//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancieraSoft.CapaDominio.Entidades.EstrategiaMora {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class ClaseEstrategiaMora : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClaseEstrategiaMora defaultInstance = ((ClaseEstrategiaMora)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClaseEstrategiaMora())));
        
        public static ClaseEstrategiaMora Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FinancieraSoft.CapaDominio.Entidades.EstrategiaMora.EstrategiaMoraPorDia")]
        public string NombreDeClaseMora {
            get {
                return ((string)(this["NombreDeClaseMora"]));
            }
        }
    }
}
