//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancieraSoft.CapaPersistencia.FabricaDAO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class ClaseFabricaDAO : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClaseFabricaDAO defaultInstance = ((ClaseFabricaDAO)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClaseFabricaDAO())));
        
        public static ClaseFabricaDAO Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FinancieraSoft.CapaPersistencia.FabricaDAO.FabricaDAO_SQLServer")]
        public string NombreDeClaseFabricaDAO {
            get {
                return ((string)(this["NombreDeClaseFabricaDAO"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a {
            get {
                return ((string)(this["a"]));
            }
            set {
                this["a"] = value;
            }
        }
    }
}
